INSERT INTO  STUDENT
(EMAIL_ADDRESS, FIRST_NAME, LAST_NAME,CREATED_DATE)
VALUES ('agam','aloni','aa@gg.com','2014-10-22');

INSERT INTO  STUDENT
(EMAIL_ADDRESS, FIRST_NAME, LAST_NAME,CREATED_DATE)
VALUES ('dani','aloni','bb@gg.com','2014-10-23');

INSERT INTO  TEACHER
(EMAIL_ADDRESS, FIRST_NAME, LAST_NAME,CREATED_DATE)
VALUES ('Yom','Tov','bb@gg.com','2014-10-23');

INSERT INTO  TEACHER
(EMAIL_ADDRESS, FIRST_NAME, LAST_NAME,CREATED_DATE)
VALUES ('Layla','Tov','bb@gg.com','2014-10-23');

INSERT INTO COURSE
(COURSE_NAME, TEACHER_ID,CREATED_DATE)
VAlUES ('Chess',1,'2014-10-23');

INSERT INTO COURSE
(COURSE_NAME, TEACHER_ID,CREATED_DATE)
VAlUES ('Chess2',2,'2022-10-23');