INSERT INTO  STUDENT
(EMAIL_ADDRESS, FIRST_NAME, LAST_NAME,CREATED_DATE)
VALUES ('agam','aloni','aa@gg.com','2014-10-22');

INSERT INTO  STUDENT
(EMAIL_ADDRESS, FIRST_NAME, LAST_NAME,CREATED_DATE)
VALUES ('dani','aloni','bb@gg.com','2014-10-23');