spring:
    application:
        name: smarti

#priorties
entities:
    - entityType: person
      attributes:
          - name: tz
            interfaces: [webint, c2]
          - name: name
            interfaces: [webint, c2]
          - name: age
            interfaces: [c2, webint]
          - name: address
            hasNested: true
            nestedAttributes:
              - name: city
                interfaces: [ c2, webint ]
              - name: region
                interfaces: [ webint, c2 ]
    - entityType: car
      attributes:
          - name: tz
            interfaces: [webint, c2]
          - name: name
            interfaces: [webint, c2]
          - name: age
            interfaces: [c2, webint]
          - name: address
            interfaces: null
            hasNested: true
            nestedAttributes:
                - name: city
                  interfaces: [c2, webint]
                - name: region
                  interfaces: [webint, c2]